name: core switch workflow

on:
  push:
    branches:
      - main
    paths:
      - 'config_file_core_switch'
  issues:
    types:
      - labeled
  workflow_dispatch:

env:
  REPO_PATH: /home/siteadmin/actions-runner/network-automation-github-actions

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    if: github.event_name == 'push' || (github.event_name == 'issues' && github.event.label.name == 'core')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes and run the 'core' script
        env:
          AUTH_TOKEN: ${{ secrets.API_AUTH_TOKEN }}
        run: |
          git pull
          ./_core.sh
        working-directory: ${{ env.REPO_PATH }}
